name: isar_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  animate_do: ^3.3.4
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  path: ^1.9.0
  path_provider: ^2.1.4
  sembast: ^3.7.4+3
  sembast_web: ^2.4.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.12


  
flutter:
  uses-material-design: true
