name: isar_example
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  go_router: ^14.2.7
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path: ^1.9.0
  path_provider: ^2.1.4
  sembast: ^3.7.3+3
  sembast_web: ^2.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.12


  
flutter:
  uses-material-design: true
